Slightly rewritten, the last version didn't succeed when it should.
Rev: src/testsuite/lshd-no-auth-test:1.2

diff --git a/src/testsuite/lshd-no-auth-test b/src/testsuite/lshd-no-auth-test
--- a/src/testsuite/lshd-no-auth-test
+++ b/src/testsuite/lshd-no-auth-test
@@ -8,7 +8,20 @@ fi
 
 . $srcdir/functions.sh
 
+set +e
+
 LSHD_FLAGS="$LSHD_FLAGS --no-password --no-publickey --no-srp"
 
-spawn_lshd || test_success
+HOME="$TEST_HOME" ../lshd -h $HOSTKEY \
+    -p $PORT --interface=$INTERFACE $LSHD_FLAGS \
+    --pid-file $PIDFILE --daemon --no-syslog "$@"
+excode=$?
+
+# Failed, but without a signal?
+
+if [ "$excode" -ne 0 -a "$excode" -lt 128 ]; then
+  test_success
+fi
+
+test_fail
 
