* src/testsuite/inetd-test: Use test_done. * src/testsuite/keygen-1-test: Likewise. * src/testsuite/keygen-2-test: Likewise. * src/testsuite/lsh-1-test: Likewise. * src/testsuite/lsh-2-test: Likewise. * src/testsuite/lsh-3-test: Likewise. * src/testsuite/lsh-5-test: Likewise. * src/testsuite/lsh-7-test: Likewise. * src/testsuite/lsh-8-test: Likewise. * src/testsuite/lsh-9-test: Likewise. * src/testsuite/lsh-encrypted-key-test: Likewise. * src/testsuite/lshd-no-auth-test: Likewise. * src/testsuite/lshg-1-test: Likewise. * src/testsuite/lshg-tcpip-local-test: Likewise. * src/testsuite/seed-test: Likewise. * src/testsuite/socks4-test: Likewise. * src/testsuite/socks5-test: Likewise. * src/testsuite/tcpip-local-in-use-test: Likewise. * src/testsuite/tcpip-local-test: Likewise. * src/testsuite/tcpip-remote-test: Likewise. * src/testsuite/write-key-1-test: Likewise. * src/testsuite/write-key-2-test: Likewise. * src/testsuite/x11-1-test: Likewise.
Rev: src/testsuite/keygen-2-test:1.9
Rev: src/testsuite/lsh-1-test:1.6
Rev: src/testsuite/lsh-2-test:1.5
Rev: src/testsuite/lsh-3-test:1.5
Rev: src/testsuite/lsh-5-test:1.4
Rev: src/testsuite/lsh-7-test:1.3
Rev: src/testsuite/lsh-8-test:1.2
Rev: src/testsuite/lsh-9-test:1.2
Rev: src/testsuite/lsh-encrypted-key-test:1.4
Rev: src/testsuite/lshd-no-auth-test:1.3
Rev: src/testsuite/lshg-1-test:1.5
Rev: src/testsuite/lshg-tcpip-local-test:1.5
Rev: src/testsuite/seed-test:1.4
Rev: src/testsuite/socks4-test:1.3
Rev: src/testsuite/socks5-test:1.3
Rev: src/testsuite/tcpip-local-in-use-test:1.2
Rev: src/testsuite/tcpip-local-test:1.9
Rev: src/testsuite/tcpip-remote-test:1.7
Rev: src/testsuite/write-key-1-test:1.3
Rev: src/testsuite/write-key-2-test:1.4
Rev: src/testsuite/x11-1-test:1.2

diff --git a/src/testsuite/seed-test b/src/testsuite/seed-test
--- a/src/testsuite/seed-test
+++ b/src/testsuite/seed-test
@@ -12,7 +12,7 @@ fi
 
 for f in test-seed-1 test-seed-2 ; do
     rm -f "$f"
-    ../lsh-make-seed --sloppy -q -o "$f" && [ -s "$f" ] || test_fail
+    ../lsh-make-seed --sloppy -q -o "$f" && [ -s "$f" ] || die "lsh-make-seed failed"
 done
 
 # Seeds should be different, so that cmp returns the exit code 1.
@@ -26,3 +26,4 @@ else
   fi
 fi
 
+test_done
