* testsuite/Makefile.am (check): Propagate EXEEXT. * testsuite/ex1-test: Use $EXEEXT. * testsuite/permute-test: Likewise.
Rev: src/argp/ChangeLog:1.40
Rev: src/argp/testsuite/Makefile.am:1.5
Rev: src/argp/testsuite/ex1-test:1.2
Rev: src/argp/testsuite/permute-test:1.4

diff --git a/src/argp/testsuite/permute-test b/src/argp/testsuite/permute-test
--- a/src/argp/testsuite/permute-test
+++ b/src/argp/testsuite/permute-test
@@ -1,5 +1,7 @@
 #! /bin/sh
 
+: ${EXEEXT:=""}
+
 # Test the somewhat hairy permuting of arguments.
 
 cat >test.out <<EOF
@@ -18,7 +20,7 @@ die () {
 for args in "-v foo bar" \
             "-v -v foo bar" "-v foo -v bar" "-v foo bar -v" \
             "foo -v bar -v" "foo bar -v -v" "foo -v -v bar" ; do
-  ./ex3 $args | diff - test.out >/dev/null || die "Test failed with args $args"
+  ./ex3$EXEEXT $args | diff - test.out >/dev/null || die "Test failed with args $args"
 done
 
 exit 0
